[package]
name = "benches_common_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false }
avian2d = { path = "../avian2d", default-features = false }
criterion = "0.5"
